name: CI-Practise-Pipeline

on: 
  push:
    branches: [ main ]  # Runs only when code is pushed to 'main'
  pull_request:
    branches: [ main ]  # Runs when someone tries to merge code

jobs:
  automation-run:
    runs-on: ubuntu-latest  # A free Linux machine provided by GitHub

    steps:
      - name: 1. Pull code from GitHub
        uses: actions/checkout@v4

      - name: 2. Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Pytest
        run: pip install -r requirements.txt

      - name: 4. Execute Tests
        run: pytest tests/test_simple.py -v